### PR TITLE
Make serialization of fractions keyed.

### PR DESCRIPTION
**Pull request by i509VCB**
This also adds more tests and splits tests into their own classes.

### CODE REVIEW

**Comment by liach** [comment]
Why? Mojang serializes a few vanilla stuff, like block positions, as non-keyed arrays. Serializing as array is usually cheaper than using keys, and this is not that hard to understand.

**Comment by LemmaEOF** [comment]
The primary worry is that streams are unordered so serializing may swap the numerator and denominator.

**Comment by kvverti** [comment]
Java streams are ordered when the backing collection is an array or a list

**Comment by LemmaEOF** [comment]
but we're just doing `IntStream.of` or `LongStream.of`, and I'm not sure we can guarantee that's an array or list

**Comment by kvverti** [comment]
Ah in the case of `IntStream.of`, [it is ordered](https://docs.oracle.com/javase/8/docs/api/java/util/stream/IntStream.html#of-int...-)

**Comment by LemmaEOF** [comment]
Should be fine, then. We might still switch it to keyed anyway but we're not sure yet. Player gave a few words on it in the channel.

**Comment by hYdos** [comment]
this been the fluid api im surprised this hasn't been bike shead'ed 
the PR also looks fine

**Review by shedaniel — APPROVED** [review]

**Comment by shedaniel** [comment]
Being keyed will be "more clear"

**Pull request merged**
